spring.application.name=Pharmacy-management-system

server.port=${PORT:8081}

spring.datasource.url=${url}
spring.datasource.username=${username}
spring.datasource.password=${password}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
##(create, update, create-drop, validate)
spring.jpa.hibernate.ddl-auto=create

# api prefix :
api.prefix=/api/v1

# cors :
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

# admin credentials :

admin_username=${admin_username}
admin_email=${admin_email}
admin_password=${admin_password}